language: python

python:
  - "3.6"

services:
  - docker

before_install:
- git clone https://github.com/DIS-SIN/bdd-test-runner
- cd bdd-test-runner
- docker-compose up

script:
  - cd tests/behave
  - behave
