language: python

python:
  - "3.6"

services:
  - docker

before_install:
- docker build -t dis-sin/bdd-test-runner
- docker run -d -p 127.0.0.1:80:4567 dis-sin/bdd-test-runner /bin/sh -c "cd /root/bdd-test-runner; bundle exec foreman start;"
- docker ps -a
- docker run dis-sin/bdd-test-runner /bin/sh -c "cd /root/bdd-test-runner; bundle exec rake test"

script:
  - cd tests/behave
  - behave
